# Snorby Database Configuration
#
# Please set your database password/user below
# NOTE: Indentation is important.
#
snorby: &snorby
  adapter: mysql
  username: snorby
  password: "hjsdfklisekue45ser"
  host: maria.ifw-dresden.de

development:
  database: snort
  <<: *snorby

test:
  database: snort
  <<: *snorby

production:
  database: snort
  <<: *snorby