# Snorby Database Configuration
#
# Please set your database password/user below
# NOTE: Indentation is important.
#
snorby: &snorby
  adapter: mysql
  username: $DB_USER
  password: "$DB_PASS"
  host: $DB_ADDRESS

development:
  database: $DB_DATABASE
  <<: *snorby

test:
  database: $DB_DATABASE
  <<: *snorby

production:
  database: $DB_DATABASE
  <<: *snorby